### ISSUE TITLE
Proposal: Introduce file:// prefix for explicit file loading in multipart data

### ISSUE THREAD

**Issue by h6ah4i** [k1LoW/runn#1073]
Hi, I noticed that the current implementation of `multipart/form-data` attempts to read a file if the specified form value is a string.

https://github.com/k1LoW/runn/blob/10bfec2fc03d0bd49d9c0bda14f08fffcdbca39e/http.go#L256:L271

This implementation caused some errors for me, and I believe the behavior can be improved by introducing a `file://` prefix.

1. runn does not raise an error if the specified file does not exist or if the provided path string is incorrect.
2. absolute file paths are not accepted.

Introducing a `file://` prefix could help address these issues and make the behavior more explicit and reliable.

**Comment by k1LoW** [comment]
@h6ah4i Thank you for your proposal!

Indeed, it is better to introduce `file://` prefix to check files strictly.

However, I would like to keep the current behavior without prefix at the side. 

This is partly for backward compatibility, but also because I want to match the behavior of other path resolution.

So, how about making it so that files are only checked strictly when a `file://` prefix is added?

Then we can introduce `file://` prefix in other path resolution implementations in the future.

**Comment by h6ah4i** [comment]
@k1LoW  Preserving backward compatibility is an important concern as well. I agree with the direction you're taking! 👍

**Comment by k1LoW** [comment]
Released as v0.122.0 👍
