### ISSUE TITLE
Support Built-in Git Repository Root Path Variable

### ISSUE THREAD

**Issue by karrybit** [k1LoW/runn#1097]
Is there a built-in variable for the file path of the Git Repository Root in the runbook? I use relative paths when reading files such as JSON in the runbook, but I must fix them every time the directory structure changes. I can solve this by passing environment variables when running, but it would be very convenient if runn supported this.

**Comment by k1LoW** [comment]
@karrybit 
Thank you for your request!

There are no plans to support Git root path.

The reason is that runn supports the execution of remote runbooks ( e.g. `http://` `github://` ), and in that case, it is not possible to obtain the Git root path.

Please use the workaround using environment variables.

**Comment by karrybit** [comment]
Thank you for confirming.
