### ISSUE TITLE
Common settings for runners

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#145]
# Proposal

Duplicate runner settings in each Runbook when creating multiple scenarios.
It would be good to define a runn configuration file and summarize in it the options that can be specified for runners and CLI execution.
Enables scenarios to be written in a reduced amount of detail and allows for separation of settings for each environment.

**Comment by k1LoW** [comment]
I did not notice this because I use runn in my Go code.

In such cases, I prefer to create a `--overlay` ( `--underlay` ) option like [customize](customize).

- https://github.com/pepabo/control-controls#overlay
- https://github.com/k1LoW/tbls-build#architecture

The target to be overwritten, or the default value, does not have to be limited to `runners:`
